[tool.poetry]
name = "notoriety"
version = "0.1.0"
description = ""
authors = ["ropeadope62 (Slurms)"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
